// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjR_NmBLwMl5J_SYQS7EB_GAae9GdvLWo',
    appId: '1:770795863594:web:e5f701cb1648d7d4670d53',
    messagingSenderId: '770795863594',
    projectId: 'chatapp-9c2a0',
    authDomain: 'chatapp-9c2a0.firebaseapp.com',
    storageBucket: 'chatapp-9c2a0.firebasestorage.app',
    measurementId: 'G-R76PY88VN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1criw934vt2R5SOeYLU10uVYQZ-WWsJ4',
    appId: '1:770795863594:android:d018fdc3db814282670d53',
    messagingSenderId: '770795863594',
    projectId: 'chatapp-9c2a0',
    storageBucket: 'chatapp-9c2a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPb2o69kN77sl2uhHgVHcdH0w0CpCQtoI',
    appId: '1:770795863594:ios:90d23e0b1c376320670d53',
    messagingSenderId: '770795863594',
    projectId: 'chatapp-9c2a0',
    storageBucket: 'chatapp-9c2a0.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPb2o69kN77sl2uhHgVHcdH0w0CpCQtoI',
    appId: '1:770795863594:ios:90d23e0b1c376320670d53',
    messagingSenderId: '770795863594',
    projectId: 'chatapp-9c2a0',
    storageBucket: 'chatapp-9c2a0.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjR_NmBLwMl5J_SYQS7EB_GAae9GdvLWo',
    appId: '1:770795863594:web:0e9c368b16943a3f670d53',
    messagingSenderId: '770795863594',
    projectId: 'chatapp-9c2a0',
    authDomain: 'chatapp-9c2a0.firebaseapp.com',
    storageBucket: 'chatapp-9c2a0.firebasestorage.app',
    measurementId: 'G-W0HV3ZH7FR',
  );
}
